### ISSUE TITLE
Auth successful, but no connection is created

### ISSUE THREAD

**Issue by xwxfox** [meister03/discord-linked-roles#3]
Using the guide and sample code, I can get everything working, the connection is available under the linked role settings on servers, however the connection doesn't show up on user profiles, and therefore the roles are not given out.

I don't know if Discord has made any breaking API changes recently, but no errors are being sent.

**Comment by meister03** [comment]
Can you go to the linked roles section and confirm, then it should finally properly link it

**Comment by xwxfox** [comment]
It shows up under linked roles, however it doesn't seem to connect the user with my application.

**Comment by meister03** [comment]
could you contact me under Discord please, I can check it our for you 
(Meister#9667)

**Comment by xwxfox** [comment]
Sure, I sent you a friend request.
